FROM apache/gravitino:1.0.0

ADD https://jdbc.postgresql.org/download/postgresql-42.7.4.jar \
    catalogs/jdbc-postgresql/libs/postgresql-42.7.4.jar

ADD https://jdbc.postgresql.org/download/postgresql-42.7.4.jar \
    catalogs/lakehouse-iceberg/libs/postgresql-42.7.4.jar

ADD https://repo1.maven.org/maven2/org/apache/iceberg/iceberg-aws-bundle/1.9.2/iceberg-aws-bundle-1.9.2.jar \
    catalogs/lakehouse-iceberg/libs/iceberg-aws-bundle-1.9.2.jar